# Generated by Django 2.2.2 on 2019-07-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solotest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='branding',
            field=models.CharField(default='branding', max_length=255),
        ),
    ]
