# Generated by Django 2.2.2 on 2019-07-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solotest', '0002_siteconfiguration_branding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='maintenance_mode',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='info',
            field=models.TextField(default='info'),
        ),
    ]
